language: ruby
before_install:
  - gem install bundler
  - gem install kramdown
  - gem install rouge
  - gem install jekyll
  - gem install jekyll-less
  - gem install therubyracer
  - gem install jekyll-press
  - gem install jekyll-sitemap
script: jekyll build -d _site
rvm:
  - 2.0.0
  - 2.1.2
  - 2.2.1
